/* ============================================================
   LOCATION DATA — countries, cities and their region/state.
   Used by the partner Add/Edit Vehicle location step (searchable
   city input). Each city is [name, region]. Add more entries here
   to expand coverage without touching dashboard logic.
   ============================================================ */
(function () {
    var GEORGIA = [
        ['Tbilisi', 'Tbilisi'],
        ['Tbilisi International Airport', 'Tbilisi'],
        ['Batumi', 'Adjara'],
        ['Batumi Airport', 'Adjara'],
        ['Kobuleti', 'Adjara'],
        ['Khelvachauri', 'Adjara'],
        ['Kutaisi', 'Imereti'],
        ['Kutaisi Airport', 'Imereti'],
        ['Tskaltubo', 'Imereti'],
        ['Zestaponi', 'Imereti'],
        ['Samtredia', 'Imereti'],
        ['Chiatura', 'Imereti'],
        ['Khoni', 'Imereti'],
        ['Vani', 'Imereti'],
        ['Sachkhere', 'Imereti'],
        ['Terjola', 'Imereti'],
        ['Rustavi', 'Kvemo Kartli'],
        ['Marneuli', 'Kvemo Kartli'],
        ['Bolnisi', 'Kvemo Kartli'],
        ['Dmanisi', 'Kvemo Kartli'],
        ['Tetritskaro', 'Kvemo Kartli'],
        ['Gardabani', 'Kvemo Kartli'],
        ['Tsalka', 'Kvemo Kartli'],
        ['Gori', 'Shida Kartli'],
        ['Khashuri', 'Shida Kartli'],
        ['Kaspi', 'Shida Kartli'],
        ['Kareli', 'Shida Kartli'],
        ['Telavi', 'Kakheti'],
        ['Sighnaghi', 'Kakheti'],
        ['Kvareli', 'Kakheti'],
        ['Gurjaani', 'Kakheti'],
        ['Sagarejo', 'Kakheti'],
        ['Dedoplistskaro', 'Kakheti'],
        ['Lagodekhi', 'Kakheti'],
        ['Akhmeta', 'Kakheti'],
        ['Akhaltsikhe', 'Samtskhe-Javakheti'],
        ['Borjomi', 'Samtskhe-Javakheti'],
        ['Bakuriani', 'Samtskhe-Javakheti'],
        ['Akhalkalaki', 'Samtskhe-Javakheti'],
        ['Ninotsminda', 'Samtskhe-Javakheti'],
        ['Aspindza', 'Samtskhe-Javakheti'],
        ['Adigeni', 'Samtskhe-Javakheti'],
        ['Mtskheta', 'Mtskheta-Mtianeti'],
        ['Stepantsminda (Kazbegi)', 'Mtskheta-Mtianeti'],
        ['Gudauri', 'Mtskheta-Mtianeti'],
        ['Dusheti', 'Mtskheta-Mtianeti'],
        ['Tianeti', 'Mtskheta-Mtianeti'],
        ['Zugdidi', 'Samegrelo-Zemo Svaneti'],
        ['Poti', 'Samegrelo-Zemo Svaneti'],
        ['Senaki', 'Samegrelo-Zemo Svaneti'],
        ['Mestia', 'Samegrelo-Zemo Svaneti'],
        ['Anaklia', 'Samegrelo-Zemo Svaneti'],
        ['Martvili', 'Samegrelo-Zemo Svaneti'],
        ['Khobi', 'Samegrelo-Zemo Svaneti'],
        ['Tsalenjikha', 'Samegrelo-Zemo Svaneti'],
        ['Chkhorotsku', 'Samegrelo-Zemo Svaneti'],
        ['Ozurgeti', 'Guria'],
        ['Ureki', 'Guria'],
        ['Lanchkhuti', 'Guria'],
        ['Chokhatauri', 'Guria'],
        ['Ambrolauri', 'Racha-Lechkhumi and Kvemo Svaneti'],
        ['Oni', 'Racha-Lechkhumi and Kvemo Svaneti'],
        ['Tsageri', 'Racha-Lechkhumi and Kvemo Svaneti']
    ];

    var ARMENIA = [
        ['Yerevan', 'Yerevan'],
        ['Zvartnots Airport', 'Yerevan'],
        ['Gyumri', 'Shirak'],
        ['Maralik', 'Shirak'],
        ['Artik', 'Shirak'],
        ['Vanadzor', 'Lori'],
        ['Spitak', 'Lori'],
        ['Stepanavan', 'Lori'],
        ['Alaverdi', 'Lori'],
        ['Tashir', 'Lori'],
        ['Akhtala', 'Lori'],
        ['Vagharshapat (Etchmiadzin)', 'Armavir'],
        ['Armavir', 'Armavir'],
        ['Metsamor', 'Armavir'],
        ['Artashat', 'Ararat'],
        ['Masis', 'Ararat'],
        ['Ararat', 'Ararat'],
        ['Vedi', 'Ararat'],
        ['Hrazdan', 'Kotayk'],
        ['Abovyan', 'Kotayk'],
        ['Charentsavan', 'Kotayk'],
        ['Tsaghkadzor', 'Kotayk'],
        ['Byureghavan', 'Kotayk'],
        ['Nor Hachn', 'Kotayk'],
        ['Gavar', 'Gegharkunik'],
        ['Sevan', 'Gegharkunik'],
        ['Martuni', 'Gegharkunik'],
        ['Vardenis', 'Gegharkunik'],
        ['Chambarak', 'Gegharkunik'],
        ['Ijevan', 'Tavush'],
        ['Dilijan', 'Tavush'],
        ['Berd', 'Tavush'],
        ['Noyemberyan', 'Tavush'],
        ['Ashtarak', 'Aragatsotn'],
        ['Aparan', 'Aragatsotn'],
        ['Talin', 'Aragatsotn'],
        ['Kapan', 'Syunik'],
        ['Goris', 'Syunik'],
        ['Sisian', 'Syunik'],
        ['Meghri', 'Syunik'],
        ['Kajaran', 'Syunik'],
        ['Agarak', 'Syunik'],
        ['Jermuk', 'Vayots Dzor'],
        ['Yeghegnadzor', 'Vayots Dzor'],
        ['Vayk', 'Vayots Dzor']
    ];

    var USA = [
        ['New York', 'New York'], ['Los Angeles', 'California'], ['Chicago', 'Illinois'],
        ['Houston', 'Texas'], ['Phoenix', 'Arizona'], ['Philadelphia', 'Pennsylvania'],
        ['San Antonio', 'Texas'], ['San Diego', 'California'], ['Dallas', 'Texas'],
        ['San Jose', 'California'], ['Austin', 'Texas'], ['Jacksonville', 'Florida'],
        ['Fort Worth', 'Texas'], ['Columbus', 'Ohio'], ['Charlotte', 'North Carolina'],
        ['San Francisco', 'California'], ['Indianapolis', 'Indiana'], ['Seattle', 'Washington'],
        ['Denver', 'Colorado'], ['Washington', 'District of Columbia'], ['Boston', 'Massachusetts'],
        ['El Paso', 'Texas'], ['Nashville', 'Tennessee'], ['Detroit', 'Michigan'],
        ['Oklahoma City', 'Oklahoma'], ['Portland', 'Oregon'], ['Las Vegas', 'Nevada'],
        ['Memphis', 'Tennessee'], ['Louisville', 'Kentucky'], ['Baltimore', 'Maryland'],
        ['Milwaukee', 'Wisconsin'], ['Albuquerque', 'New Mexico'], ['Tucson', 'Arizona'],
        ['Fresno', 'California'], ['Sacramento', 'California'], ['Kansas City', 'Missouri'],
        ['Mesa', 'Arizona'], ['Atlanta', 'Georgia'], ['Omaha', 'Nebraska'],
        ['Colorado Springs', 'Colorado'], ['Raleigh', 'North Carolina'], ['Long Beach', 'California'],
        ['Virginia Beach', 'Virginia'], ['Miami', 'Florida'], ['Oakland', 'California'],
        ['Minneapolis', 'Minnesota'], ['Tulsa', 'Oklahoma'], ['Bakersfield', 'California'],
        ['Wichita', 'Kansas'], ['Arlington', 'Texas'], ['Aurora', 'Colorado'],
        ['Tampa', 'Florida'], ['New Orleans', 'Louisiana'], ['Cleveland', 'Ohio'],
        ['Honolulu', 'Hawaii'], ['Anaheim', 'California'], ['Lexington', 'Kentucky'],
        ['Stockton', 'California'], ['Corpus Christi', 'Texas'], ['Henderson', 'Nevada'],
        ['Riverside', 'California'], ['Newark', 'New Jersey'], ['Saint Paul', 'Minnesota'],
        ['Santa Ana', 'California'], ['Cincinnati', 'Ohio'], ['Irvine', 'California'],
        ['Orlando', 'Florida'], ['Pittsburgh', 'Pennsylvania'], ['St. Louis', 'Missouri'],
        ['Greensboro', 'North Carolina'], ['Jersey City', 'New Jersey'], ['Anchorage', 'Alaska'],
        ['Lincoln', 'Nebraska'], ['Plano', 'Texas'], ['Durham', 'North Carolina'],
        ['Buffalo', 'New York'], ['Chandler', 'Arizona'], ['Chula Vista', 'California'],
        ['Toledo', 'Ohio'], ['Madison', 'Wisconsin'], ['Gilbert', 'Arizona'],
        ['Reno', 'Nevada'], ['Fort Wayne', 'Indiana'], ['North Las Vegas', 'Nevada'],
        ['St. Petersburg', 'Florida'], ['Lubbock', 'Texas'], ['Irving', 'Texas'],
        ['Laredo', 'Texas'], ['Winston-Salem', 'North Carolina'], ['Chesapeake', 'Virginia'],
        ['Glendale', 'Arizona'], ['Garland', 'Texas'], ['Scottsdale', 'Arizona'],
        ['Norfolk', 'Virginia'], ['Boise', 'Idaho'], ['Fremont', 'California'],
        ['Spokane', 'Washington'], ['Santa Clarita', 'California'], ['Baton Rouge', 'Louisiana'],
        ['Richmond', 'Virginia'], ['Hialeah', 'Florida'], ['San Bernardino', 'California'],
        ['Tacoma', 'Washington'], ['Modesto', 'California'], ['Huntsville', 'Alabama'],
        ['Des Moines', 'Iowa'], ['Yonkers', 'New York'], ['Rochester', 'New York'],
        ['Moreno Valley', 'California'], ['Fayetteville', 'North Carolina'], ['Fontana', 'California'],
        ['Columbus', 'Georgia'], ['Worcester', 'Massachusetts'], ['Port St. Lucie', 'Florida'],
        ['Little Rock', 'Arkansas'], ['Augusta', 'Georgia'], ['Oxnard', 'California'],
        ['Birmingham', 'Alabama'], ['Montgomery', 'Alabama'], ['Frisco', 'Texas'],
        ['Amarillo', 'Texas'], ['Salt Lake City', 'Utah'], ['Grand Rapids', 'Michigan'],
        ['Huntington Beach', 'California'], ['Overland Park', 'Kansas'], ['Glendale', 'California'],
        ['Tallahassee', 'Florida'], ['Grand Prairie', 'Texas'], ['McKinney', 'Texas'],
        ['Cape Coral', 'Florida'], ['Sioux Falls', 'South Dakota'], ['Peoria', 'Arizona'],
        ['Providence', 'Rhode Island'], ['Vancouver', 'Washington'], ['Knoxville', 'Tennessee'],
        ['Akron', 'Ohio'], ['Shreveport', 'Louisiana'], ['Mobile', 'Alabama'],
        ['Brownsville', 'Texas'], ['Newport News', 'Virginia'], ['Fort Lauderdale', 'Florida'],
        ['Chattanooga', 'Tennessee'], ['Tempe', 'Arizona'], ['Aurora', 'Illinois'],
        ['Santa Rosa', 'California'], ['Eugene', 'Oregon'], ['Elk Grove', 'California'],
        ['Salem', 'Oregon'], ['Ontario', 'California'], ['Cary', 'North Carolina'],
        ['Rancho Cucamonga', 'California'], ['Oceanside', 'California'], ['Lancaster', 'California'],
        ['Garden Grove', 'California'], ['Pembroke Pines', 'Florida'], ['Fort Collins', 'Colorado'],
        ['Palmdale', 'California'], ['Springfield', 'Missouri'], ['Clarksville', 'Tennessee'],
        ['Salinas', 'California'], ['Hayward', 'California'], ['Paterson', 'New Jersey'],
        ['Alexandria', 'Virginia'], ['Macon', 'Georgia'], ['Corona', 'California'],
        ['Kansas City', 'Kansas'], ['Lakewood', 'Colorado'], ['Springfield', 'Massachusetts'],
        ['Sunnyvale', 'California'], ['Jackson', 'Mississippi'], ['Killeen', 'Texas'],
        ['Hollywood', 'Florida'], ['Pasadena', 'Texas'], ['Charleston', 'South Carolina'],
        ['Pomona', 'California'], ['Escondido', 'California'], ['Naperville', 'Illinois'],
        ['Joliet', 'Illinois'], ['Bellevue', 'Washington'], ['Rockford', 'Illinois'],
        ['Savannah', 'Georgia'], ['Torrance', 'California'], ['Bridgeport', 'Connecticut'],
        ['Fullerton', 'California'], ['Mesquite', 'Texas'], ['Syracuse', 'New York'],
        ['Surprise', 'Arizona'], ['McAllen', 'Texas'], ['Thornton', 'Colorado'],
        ['Roseville', 'California'], ['Denton', 'Texas'], ['Midland', 'Texas'],
        ['Carrollton', 'Texas'], ['Charleston', 'West Virginia'], ['Warren', 'Michigan'],
        ['Columbia', 'South Carolina'], ['Hampton', 'Virginia'], ['Coral Springs', 'Florida'],
        ['Visalia', 'California'], ['Sterling Heights', 'Michigan'], ['New Haven', 'Connecticut'],
        ['Cedar Rapids', 'Iowa'], ['Stamford', 'Connecticut'], ['Concord', 'California'],
        ['Kent', 'Washington'], ['Santa Clara', 'California'], ['Elizabeth', 'New Jersey'],
        ['Round Rock', 'Texas'], ['Lafayette', 'Louisiana'], ['Gainesville', 'Florida'],
        ['Topeka', 'Kansas'], ['Athens', 'Georgia'], ['Boulder', 'Colorado'],
        ['Wilmington', 'North Carolina'], ['Allentown', 'Pennsylvania'], ['Evansville', 'Indiana'],
        ['Berkeley', 'California'], ['Provo', 'Utah'], ['Norman', 'Oklahoma'],
        ['Abilene', 'Texas'], ['Columbia', 'Missouri'], ['Hartford', 'Connecticut'],
        ['Fargo', 'North Dakota'], ['Billings', 'Montana'], ['Burlington', 'Vermont'],
        ['Manchester', 'New Hampshire'], ['Portland', 'Maine'], ['Wilmington', 'Delaware'],
        ['Cheyenne', 'Wyoming'], ['Dover', 'Delaware'], ['Pierre', 'South Dakota'],
        ['Helena', 'Montana'], ['Juneau', 'Alaska'], ['Frankfort', 'Kentucky'],
        ['Trenton', 'New Jersey'], ['Annapolis', 'Maryland'], ['Concord', 'New Hampshire'],
        ['Montpelier', 'Vermont'], ['Carson City', 'Nevada'], ['Olympia', 'Washington'],
        ['Tallahassee', 'Florida'], ['Jefferson City', 'Missouri'], ['Bismarck', 'North Dakota'],
        ['Augusta', 'Maine'], ['Springfield', 'Illinois'], ['Lansing', 'Michigan']
    ];

    var TURKEY = [
        ['Istanbul', 'Istanbul'],
        ['Istanbul Airport', 'Istanbul'],
        ['Sabiha Gokcen Airport', 'Istanbul'],
        ['Ankara', 'Ankara'],
        ['Esenboga Airport', 'Ankara'],
        ['Izmir', 'Izmir'],
        ['Izmir Adnan Menderes Airport', 'Izmir'],
        ['Antalya', 'Antalya'],
        ['Antalya Airport', 'Antalya'],
        ['Alanya', 'Antalya'],
        ['Bodrum', 'Mugla'],
        ['Bodrum-Milas Airport', 'Mugla'],
        ['Dalaman', 'Mugla'],
        ['Dalaman Airport', 'Mugla'],
        ['Fethiye', 'Mugla'],
        ['Marmaris', 'Mugla'],
        ['Trabzon', 'Trabzon'],
        ['Trabzon Airport', 'Trabzon'],
        ['Bursa', 'Bursa'],
        ['Adana', 'Adana'],
        ['Gaziantep', 'Gaziantep'],
        ['Konya', 'Konya'],
        ['Kayseri', 'Kayseri'],
        ['Nevsehir (Cappadocia)', 'Nevsehir'],
        ['Denizli (Pamukkale)', 'Denizli'],
        ['Samsun', 'Samsun'],
        ['Eskisehir', 'Eskisehir']
    ];

    var RUSSIA = [
        ['Moscow', 'Moscow'],
        ['Sheremetyevo Airport', 'Moscow'],
        ['Domodedovo Airport', 'Moscow'],
        ['Vnukovo Airport', 'Moscow'],
        ['Saint Petersburg', 'Saint Petersburg'],
        ['Pulkovo Airport', 'Saint Petersburg'],
        ['Sochi', 'Krasnodar Krai'],
        ['Sochi Airport', 'Krasnodar Krai'],
        ['Krasnodar', 'Krasnodar Krai'],
        ['Krasnodar Airport', 'Krasnodar Krai'],
        ['Kazan', 'Tatarstan'],
        ['Kazan Airport', 'Tatarstan'],
        ['Yekaterinburg', 'Sverdlovsk'],
        ['Koltsovo Airport', 'Sverdlovsk'],
        ['Novosibirsk', 'Novosibirsk'],
        ['Tolmachevo Airport', 'Novosibirsk'],
        ['Nizhny Novgorod', 'Nizhny Novgorod'],
        ['Rostov-on-Don', 'Rostov'],
        ['Samara', 'Samara'],
        ['Ufa', 'Bashkortostan'],
        ['Krasnoyarsk', 'Krasnoyarsk Krai'],
        ['Vladivostok', 'Primorsky Krai'],
        ['Kaliningrad', 'Kaliningrad'],
        ['Volgograd', 'Volgograd'],
        ['Perm', 'Perm Krai'],
        ['Chelyabinsk', 'Chelyabinsk']
    ];

    function toObjs(arr) {
        return arr.map(function (c) { return { name: c[0], region: c[1] }; });
    }

    window.LOCATION_DATA = {
        georgia: { label: 'Georgia', cities: toObjs(GEORGIA) },
        armenia: { label: 'Armenia', cities: toObjs(ARMENIA) },
        turkey: { label: 'Turkey', cities: toObjs(TURKEY) },
        russia: { label: 'Russia', cities: toObjs(RUSSIA) },
        usa: { label: 'United States', cities: toObjs(USA) }
    };
})();
